id: youtube-slack
enabled: true
trigger:
  connector: youtube
  event: video.published
  filters:
    channel_id:
      equals: UCDvErgK0j5ur3aLgn6U-LqQ
actions:
  - id: notify-slack
    type: slack
    connection_id: slack
    channel: C01BQC114P2
    text: |-
      New video on our YouTube channel!

      {title}

      Link: {url}
    unfurl_links: true
